hyperskill_project:
  id: 74
  ide_files: https://stepik.org/media/attachments/lesson/240846/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Tue, 03 Jan 2023 23:58:28 UTC"
stages:
- id: 409
  step: 6590
  is_completed: true
- id: 410
  step: 6591
  is_completed: true
- id: 411
  step: 6592
  is_completed: true
- id: 412
  step: 6593
  is_completed: true
- id: 413
  step: 6594
  is_completed: true
- id: 414
  step: 6595
  is_completed: true
- id: 415
  step: 6596
  is_completed: true
topics:
  0:
  - title: Immutability
    theory_id: 7929
  - title: Computer programming
    theory_id: 8739
  - title: Paradigms
    theory_id: 15860
  - title: Introduction to OOP
    theory_id: 3614
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Taking input
    theory_id: 5913
  - title: Naming variables
    theory_id: 5885
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: For loop
    theory_id: 6065
  - title: While loop
    theory_id: 5940
  - title: Basic data types
    theory_id: 5852
  - title: Variables
    theory_id: 5859
  - title: Invoking a function
    theory_id: 5891
  - title: Integer arithmetic
    theory_id: 5865
  - title: List
    theory_id: 5979
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: Indexes
    theory_id: 6189
  - title: Basic string methods
    theory_id: 6842
  - title: Type casting
    theory_id: 6224
  - title: Escape sequences
    theory_id: 7130
  - title: Split and join
    theory_id: 6972
  - title: Dictionary
    theory_id: 6481
  - title: Set
    theory_id: 6643
  - title: Tuple
    theory_id: 7462
  - title: How to choose a collection to use
    theory_id: 13907
  1:
  - title: Else statement
    theory_id: 5932
  - title: Loop control statements
    theory_id: 6302
  - title: Elif statement
    theory_id: 5926
  2:
  - title: Declaring a function
    theory_id: 5900
  - title: Arguments
    theory_id: 7248
  - title: List comprehension
    theory_id: 6315
  - title: Operations with list
    theory_id: 6031
  3:
  - title: IDE
    theory_id: 10996
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Computer algorithms
    theory_id: 16547
  - title: The big O notation
    theory_id: 16699
  - title: "Best, average and worst cases"
    theory_id: 20084
  - title: String basics
    theory_id: 19445
  - title: Load module
    theory_id: 6019
  - title: Create module
    theory_id: 6057
  - title: Packages
    theory_id: 6384
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: Pip
    theory_id: 6230
  - title: Virtual Environment
    theory_id: 13923
  - title: Pseudocode
    theory_id: 15090
  - title: Pseudocode basics
    theory_id: 19510
  - title: Complex constructions in pseudocode
    theory_id: 20922
  - title: PyCharm basics
    theory_id: 6193
  - title: Running Python applications in PyCharm
    theory_id: 19153
  - title: Intro to computational thinking
    theory_id: 8742
  - title: Components of computational thinking
    theory_id: 8745
  - title: Searching a substring
    theory_id: 5194
  - title: Search in a string
    theory_id: 9558
  - title: Functional decomposition
    theory_id: 9571
  4:
  - title: Data structures
    theory_id: 16927
  - title: Class
    theory_id: 6661
  - title: Class instances
    theory_id: 6669
  - title: Methods
    theory_id: 6931
  - title: Methods and attributes
    theory_id: 6981
  - title: Magic methods
    theory_id: 7139
  - title: Program execution
    theory_id: 6047
  - title: Errors
    theory_id: 6052
  - title: Exceptions
    theory_id: 6042
  - title: Built-in exceptions
    theory_id: 11680
  - title: Exception handling
    theory_id: 6270
  - title: Inheritance
    theory_id: 9844
  - title: Inheritance in Python
    theory_id: 7235
  - title: Polymorphism
    theory_id: 10027
  - title: Method overriding
    theory_id: 7629
  - title: User-defined exceptions
    theory_id: 10217
  - title: Assert statement
    theory_id: 10372
  - title: Scopes
    theory_id: 6322
  - title: String formatting
    theory_id: 6037
  5:
  - title: Docstrings
    theory_id: 11869
  - title: Class vs instance
    theory_id: 6677
  - title: Identity testing
    theory_id: 8077
  - title: Objects in Python
    theory_id: 9262
  - title: Dictionary methods
    theory_id: 9008
  - title: Operations with dictionary
    theory_id: 11096
  - title: Default arguments
    theory_id: 10295
  - title: Args
    theory_id: 8560
  - title: Kwargs
    theory_id: 9544
  - title: Function annotations
    theory_id: 15664
  - title: "Hashing: overview"
    theory_id: 9831
  - title: Hash function
    theory_id: 10878
  - title: Hash table
    theory_id: 13054
  - title: Hashable
    theory_id: 7823
  6:
  - title: Stack
    theory_id: 5252
  - title: Queue
    theory_id: 20716
  - title: Deque
    theory_id: 18635
  - title: Algorithms in Python
    theory_id: 7316
  - title: Stack in Python
    theory_id: 8915
  - title: Queue in Python
    theory_id: 8925
